const colorIntro = '#8FFF9A';
const colorAccionCreciente = '#FF7B5E';
const colorClimax = '#CF1E1E';
const colorDecreciente= '#FFFBA3';
const colorResolucion = '#7EFFFF';


const cardsDataNarrative = [
    { color: colorIntro, stroke:colorIntro, hoverImage: '/images/narrative/narrative2.png' },
    { color: colorIntro, stroke:colorIntro, hoverImage: '/images/narrative/narrative3.png' },
    { color: colorAccionCreciente, stroke:colorAccionCreciente, hoverImage: '/images/narrative/narrative4.png' },
    { color: colorClimax, stroke:colorClimax, hoverImage: '/images/narrative/narrative5.png' },
    { color: colorDecreciente, stroke:colorDecreciente, hoverImage: '/images/narrative/narrative6.png' },
    { color: colorIntro, stroke:colorIntro, hoverImage: '/images/narrative/narrative7.png' },
    { color: colorIntro, stroke:colorIntro, hoverImage: '/images/narrative/narrative8.png' },
    { color: colorIntro, stroke:colorIntro, hoverImage: '/images/narrative/narrative13.png' },
    { color: colorAccionCreciente, stroke:colorAccionCreciente, hoverImage: '/images/narrative/narrative15.png' },
    { color: colorAccionCreciente, stroke:colorAccionCreciente, hoverImage: '/images/narrative/narrative16.png' },
    { color: colorClimax, stroke:colorClimax, hoverImage: '/images/narrative/narrative19.png' },
    { color: colorIntro, stroke:colorIntro, hoverImage: '/images/narrative/narrative21.png' },
    { color: colorIntro, stroke:colorIntro, hoverImage: '/images/narrative/narrative24.png' },
    { color: colorIntro, stroke:colorIntro, hoverImage: '/images/narrative/narrative29.png' },
    { color: colorIntro, stroke:colorIntro, hoverImage: '/images/narrative/narrative32.png' },
    { color: colorIntro, stroke:colorIntro, hoverImage: '/images/narrative/narrative34.png' },
    { color: colorAccionCreciente, stroke:colorAccionCreciente, hoverImage: '/images/narrative/narrative35.png' },
    { color: colorAccionCreciente, stroke:colorAccionCreciente, hoverImage: '/images/narrative/narrative37.png' },
    { color: colorClimax, stroke:colorClimax, hoverImage: '/images/narrative/narrative48.png' },
    { color: colorClimax, stroke:colorClimax, hoverImage: '/images/narrative/narrative43.png' },
    { color: colorDecreciente, stroke:colorDecreciente, hoverImage: '/images/narrative/narrative45.png' },
    { color: colorDecreciente, stroke:colorDecreciente, hoverImage: '/images/narrative/narrative49.png' },
    { color: colorResolucion, stroke:colorResolucion, hoverImage: '/images/narrative/narrative53.png' },
    { color: colorIntro, stroke:colorIntro, hoverImage: '/images/narrative/narrative57.png' },
    { color: colorIntro, stroke:colorIntro, hoverImage: '/images/narrative/narrative58.png' },
    { color: colorIntro, stroke:colorIntro, hoverImage: '/images/narrative/narrative59.png' },
    { color: colorAccionCreciente, stroke:colorAccionCreciente, hoverImage: '/images/narrative/narrative67.png' },
    { color: colorAccionCreciente, stroke:colorAccionCreciente, hoverImage: '/images/narrative/narrative69.png' },
    { color: colorClimax, stroke:colorClimax, hoverImage: '/images/narrative/narrative83.png' },
    { color: colorResolucion, stroke:colorResolucion, hoverImage: '/images/narrative/narrative89.png' },
  ];

  const cardsDataColor = [
    { color: '#3A3328', stroke:'#EAE2DC', hoverImage: '/images/narrative/narrative2.png' },
    { color: '#81624F', stroke:'#040807', hoverImage: '/images/narrative/narrative3.png' },
    { color: '#E6D6C0', stroke:'#C5B97B', hoverImage: '/images/narrative/narrative4.png' },
    { color: '#B29276', stroke:'#060606', hoverImage: '/images/narrative/narrative5.png' },
    { color: '#77849B', stroke:'#E3BD8E', hoverImage: '/images/narrative/narrative6.png' },
    { color: '#030506', stroke:'#3C3B3F', hoverImage: '/images/narrative/narrative7.png' },
    { color: '#BECCC8', stroke:'#961136', hoverImage: '/images/narrative/narrative8.png' },
    { color: '#7B9AA5', stroke:'#040404', hoverImage: '/images/narrative/narrative13.png' },
    { color: '#F8F6F8', stroke:'#3D221F', hoverImage: '/images/narrative/narrative15.png' },
    { color: '#2C6C94', stroke:'#61140E', hoverImage: '/images/narrative/narrative16.png' },
    { color: '#211818', stroke:'#FDEBE1', hoverImage: '/images/narrative/narrative19.png' },
    { color: '#020404', stroke:'#A6A3A5', hoverImage: '/images/narrative/narrative21.png' },
    { color: '#BBBDBE', stroke:'#7396B7', hoverImage: '/images/narrative/narrative24.png' },
    { color: '#161B22', stroke:'#B57AB7', hoverImage: '/images/narrative/narrative29.png' },
    { color: '#252F40', stroke:'#B57AB7', hoverImage: '/images/narrative/narrative32.png' },
    { color: '#BBB6BC', stroke:'#911913', hoverImage: '/images/narrative/narrative34.png' },
    { color: '#341821', stroke:'#BF2517', hoverImage: '/images/narrative/narrative35.png' },
    { color: '#3E070C', stroke:'#90674F', hoverImage: '/images/narrative/narrative37.png' },
    { color: '#BF1828', stroke:'#060000', hoverImage: '/images/narrative/narrative48.png' },
    { color: '#020300', stroke:'#DAA451', hoverImage: '/images/narrative/narrative43.png' },
    { color: '#3D434E', stroke:'#D49F66', hoverImage: '/images/narrative/narrative45.png' },
    { color: '#AA1B13', stroke:'#AA1B13', hoverImage: '/images/narrative/narrative49.png' },
    { color: '#710A07', stroke:'#508374', hoverImage: '/images/narrative/narrative53.png' },
    { color: '#212D35', stroke:'#A9AEBE', hoverImage: '/images/narrative/narrative57.png' },
    { color: '#C198AF', stroke:'#C79858', hoverImage: '/images/narrative/narrative58.png' },
    { color: '#2D6463', stroke:'#FAE3B0', hoverImage: '/images/narrative/narrative59.png' },
    { color: '#63756F', stroke:'#4B4E21', hoverImage: '/images/narrative/narrative67.png' },
    { color: '#77514F', stroke:'#E6404E', hoverImage: '/images/narrative/narrative69.png' },
    { color: '#A8B6BF', stroke:'#28282A', hoverImage: '/images/narrative/narrative83.png' },
    { color: '#CED5E4', stroke:'#C1CEE4', hoverImage: '/images/narrative/narrative89.png' },
  ];